import Header from "@/components/Header";
import SearchBar from "@/components/SearchBar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen container mx-auto px-4 lg:px-8 lg:py-4 bg-[#f5f3ef] rounded`}
      >
        <Header />
        <SearchBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
